//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class USER
    {

        public decimal ID { get; set; }

        [Required]
        public string NAME { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string PASSWORD { get; set; }

        [EmailAddress]
        public string EMAIL { get; set; }
    }
}
