//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASEPro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CASE_JEntities : DbContext
    {
        public CASE_JEntities()
            : base("name=CASE_JEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CASO_USO_DEPENDENCIAS> CASO_USO_DEPENDENCIAS { get; set; }
        public DbSet<CASO_USO_DETALLES> CASO_USO_DETALLES { get; set; }
        public DbSet<CASOS_USOS> CASOS_USOS { get; set; }
        public DbSet<DETALLE_TIPOS> DETALLE_TIPOS { get; set; }
        public DbSet<DOCUMENTO> DOCUMENTOS { get; set; }
        public DbSet<INTEGRANTE> INTEGRANTES { get; set; }
        public DbSet<OPERACIONE> OPERACIONES { get; set; }
        public DbSet<PROYECTO_DETALLES> PROYECTO_DETALLES { get; set; }
        public DbSet<PROYECTO> PROYECTOS { get; set; }
        public DbSet<REQUERIMIENTO_CATEGORIAS> REQUERIMIENTO_CATEGORIAS { get; set; }
        public DbSet<REQUERIMIENTO_DEPENDENCIAS> REQUERIMIENTO_DEPENDENCIAS { get; set; }
        public DbSet<REQUERIMIENTO_DETALLES> REQUERIMIENTO_DETALLES { get; set; }
        public DbSet<REQUERIMIENTO_ESTADOS> REQUERIMIENTO_ESTADOS { get; set; }
        public DbSet<REQUERIMIENTO_TIPOS> REQUERIMIENTO_TIPOS { get; set; }
        public DbSet<REQUERIMIENTO> REQUERIMIENTOS { get; set; }
        public DbSet<ROLE> ROLES { get; set; }
        public DbSet<USUARIO> USUARIOS { get; set; }
    }
}
