//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASEPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROYECTO
    {
        public PROYECTO()
        {
            this.INTEGRANTES = new HashSet<INTEGRANTE>();
            this.PROYECTO_DETALLES = new HashSet<PROYECTO_DETALLES>();
            this.REQUERIMIENTOS = new HashSet<REQUERIMIENTO>();
        }
    
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public string OBJETIVOPRIMARIO { get; set; }
        public string ALCANCE { get; set; }
        public decimal PRIORIDAD { get; set; }
        public decimal FASE { get; set; }
        public string VERSION { get; set; }
    
        public virtual ICollection<INTEGRANTE> INTEGRANTES { get; set; }
        public virtual ICollection<PROYECTO_DETALLES> PROYECTO_DETALLES { get; set; }
        public virtual ICollection<REQUERIMIENTO> REQUERIMIENTOS { get; set; }
    }
}
