//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASEPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUERIMIENTO
    {
        public REQUERIMIENTO()
        {
            this.DOCUMENTOS = new HashSet<DOCUMENTO>();
            this.REQUERIMIENTO_DEPENDENCIAS = new HashSet<REQUERIMIENTO_DEPENDENCIAS>();
            this.REQUERIMIENTO_DEPENDENCIAS1 = new HashSet<REQUERIMIENTO_DEPENDENCIAS>();
            this.REQUERIMIENTO_DETALLES = new HashSet<REQUERIMIENTO_DETALLES>();
            this.CASOS_USOS = new HashSet<CASOS_USOS>();
        }
    
        public decimal ID { get; set; }
        public string CODIGO { get; set; }
        public string TITULO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal COMPLEJIDAD { get; set; }
        public System.DateTime FECHAREVISION { get; set; }
        public decimal COSTOESTIMADO { get; set; }
        public string LINEABASE { get; set; }
        public decimal PROYECTO_ID { get; set; }
        public decimal TIPO_ID { get; set; }
        public decimal CATEGORIA_ID { get; set; }
        public decimal ESTADO_ID { get; set; }
        public decimal RESPONSABLE_ID { get; set; }
        public decimal CREADOR_ID { get; set; }
    
        public virtual ICollection<DOCUMENTO> DOCUMENTOS { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
        public virtual REQUERIMIENTO_CATEGORIAS REQUERIMIENTO_CATEGORIAS { get; set; }
        public virtual ICollection<REQUERIMIENTO_DEPENDENCIAS> REQUERIMIENTO_DEPENDENCIAS { get; set; }
        public virtual ICollection<REQUERIMIENTO_DEPENDENCIAS> REQUERIMIENTO_DEPENDENCIAS1 { get; set; }
        public virtual ICollection<REQUERIMIENTO_DETALLES> REQUERIMIENTO_DETALLES { get; set; }
        public virtual REQUERIMIENTO_ESTADOS REQUERIMIENTO_ESTADOS { get; set; }
        public virtual REQUERIMIENTO_TIPOS REQUERIMIENTO_TIPOS { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual ICollection<CASOS_USOS> CASOS_USOS { get; set; }
    }
}
