//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASEPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUERIMIENTO_DEPENDENCIAS
    {
        public decimal REQ_ID { get; set; }
        public decimal REQ_DEPENDENDE_ID { get; set; }
        public string TIPO_DEPENDENCIA { get; set; }
    
        public virtual REQUERIMIENTO REQUERIMIENTO { get; set; }
        public virtual REQUERIMIENTO REQUERIMIENTO1 { get; set; }
    }
}
