//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASEPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUERIMIENTO_TIPOS
    {
        public REQUERIMIENTO_TIPOS()
        {
            this.REQUERIMIENTOS = new HashSet<REQUERIMIENTO>();
        }
    
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<REQUERIMIENTO> REQUERIMIENTOS { get; set; }
    }
}
